name: reels_player
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.5
  device_info_plus: ^10.1.2
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  package_info_plus: ^8.0.2
  video_player: ^2.9.1
  visibility_detector: ^0.4.0+2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
